<a href="https://colab.research.google.com/github/przemekpardyak/colab/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.current_device())
print(torch.cuda.get_device_name(0))




2.11.0+cu128
True
1
0
Tesla T4


In [26]:
print(torch.tensor(1))
print(torch.tensor([1, 2]))
print(torch.tensor([[1, 2],[3, 4]]))
print(torch.tensor([[[1, 2],[3, 4]],[[11, 22],[33, 44]]]))

t0a = torch.tensor(1)
print(t0a.dtype)
t0b = torch.tensor(1.0)
print(t0b.dtype)

t3 = torch.tensor([[[1, 2, 3],[4, 5, 6]],[[11, 22, 33],[44, 55, 66]]])
print(t3)
print("shape:", t3.shape)
print("view:", t3.view(3, 2, 2))
print("reshape:", t3.reshape(3, 2, 2))
print("reshape:", t3.reshape(2, 3, 2))
print("reshape:", t3.reshape(12))

t2 = torch.tensor([[1, 2, 3],[4, 5, 6]])
print(t2)
print("T:", t2.T)
print("M:", t2.matmul(t2.T))
print("M:", t2 @ t2.T)



tensor(1)
tensor([1, 2])
tensor([[1, 2],
        [3, 4]])
tensor([[[ 1,  2],
         [ 3,  4]],

        [[11, 22],
         [33, 44]]])
torch.int64
torch.float32
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[11, 22, 33],
         [44, 55, 66]]])
shape: torch.Size([2, 2, 3])
view: tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [11, 22]],

        [[33, 44],
         [55, 66]]])
reshape: tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [11, 22]],

        [[33, 44],
         [55, 66]]])
reshape: tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[11, 22],
         [33, 44],
         [55, 66]]])
reshape: tensor([ 1,  2,  3,  4,  5,  6, 11, 22, 33, 44, 55, 66])
tensor([[1, 2, 3],
        [4, 5, 6]])
T: tensor([[1, 4],
        [2, 5],
        [3, 6]])
M: tensor([[14, 32],
        [32, 77]])
M: tensor([[14, 32],
        [32, 77]])
